#!/usr/bin/env python3
"""Discover active Flins projects and write a non-destructive consolidated audit."""
from __future__ import annotations
import argparse, json, subprocess, sys
from pathlib import Path
sys.path.insert(0,str(Path(__file__).resolve().parent)); import ip_provenance as IP

def public_remote(root:Path)->str:
    r=subprocess.run(["git","-c",f"safe.directory={root.as_posix()}","-C",str(root),"remote","get-url","origin"],capture_output=True,text=True)
    return "YES" if "github.com" in r.stdout.lower() else "UNKNOWN"

def discover(workspace:Path,harness:Path)->list[Path]:
    roots={harness.resolve()}; registry=harness/"PROCESS_APPS.json"
    if registry.is_file():
        for x in json.loads(registry.read_text(encoding="utf-8")).get("apps",[]):
            p=(workspace/x["path"]).resolve()
            if p.is_dir(): roots.add(p)
    for p in workspace.iterdir():
        if not p.is_dir() or p.name.startswith(".") or p.name in {"worktrees","handoffs","outputs","review-runtime","release-evidence"}: continue
        if (p/"project.godot").is_file() or (p/"game/game.json").is_file() or (p/".openai/hosting.json").is_file(): roots.add(p.resolve())
    return sorted(roots,key=lambda x:str(x).lower())

def enrich(report:dict)->dict:
    public=public_remote(Path(report["root"])); report["public_repository"]=public
    for f in report["findings"]:
        if public=="YES" and f["code"]=="UNREGISTERED_PRODUCTION_ASSET":
            f["severity"]="ORANGE"
            f["code"]="PUBLIC_UNVERIFIED_RAW_ASSET"
            f["reason"]="tracked raw production asset is exposed in a public repository while provenance and redistribution rights are unverified"
        code=f["code"]; f.update({
            "what_it_is":"production/distribution asset or dependency record",
            "known_source":"UNKNOWN",
            "known_license":"UNKNOWN",
            "currently_ships":"UNKNOWN",
            "exists_in_public_repository":public,
            "likely_practical_exposure":"Raw tracked file may be downloadable" if public=="YES" else "UNKNOWN",
            "recommended_remediation":"VERIFY provenance and license; then register exact evidence" if "UNREGISTERED" in code or "UNKNOWN" in code or "MISSING" in code else "INVESTIGATE and resolve the declared risk",
            "replacement_readily_possible":"UNKNOWN",
            "attribution_alone_may_resolve":"POSSIBLY" if "ATTRIBUTION" in code or "NOTICE" in code else "UNKNOWN",
            "evidence":f.get("path","registry")+" and governance registry",
            "uncertainty_remaining":f["reason"],
        })
    return report

def render(reports:list[dict])->str:
    counts={x:0 for x in ("GREEN","YELLOW","ORANGE","RED")}
    for r in reports:
        for f in r["findings"]: counts[f["severity"]]=counts.get(f["severity"],0)+1
    lines=["# FLINS_APP_VAULT_IP_PROVENANCE_AUDIT","", "Generated by a read-only evidence audit. This is compliance engineering, not a legal opinion.","", "## Scope","",f"Projects audited: {len(reports)}",""]
    lines += [f"- `{r['application']}` — `{r['root']}` — public repository: {r['public_repository']}" for r in reports]
    lines += ["","## Summary","",f"- GREEN: {counts['GREEN']}",f"- YELLOW: {counts['YELLOW']}",f"- ORANGE: {counts['ORANGE']}",f"- RED: {counts['RED']}",""]
    for sev in ("GREEN","YELLOW","ORANGE","RED"):
        lines += [f"## {sev}",""]
        found=[(r,f) for r in reports for f in r["findings"] if f["severity"]==sev]
        if not found: lines += ["No findings in this classification.",""]; continue
        for n,(r,f) in enumerate(found,1):
            lines += [f"### {sev}-{n}: {r['application']} — {f['id']}","",f"- Application: {r['application']}",f"- Asset/dependency: {f['id']}",f"- File/path: `{f.get('path','UNKNOWN')}`",f"- What it is: {f['what_it_is']}",f"- Known source: {f['known_source']}",f"- Known license: {f['known_license']}",f"- Why flagged: {f['reason']}",f"- Currently ships: {f['currently_ships']}",f"- Public repository: {f['exists_in_public_repository']}",f"- Likely exposure: {f['likely_practical_exposure']}",f"- Recommended remediation: {f['recommended_remediation']}",f"- Replacement readily possible: {f['replacement_readily_possible']}",f"- Attribution alone may resolve: {f['attribution_alone_may_resolve']}",f"- Evidence: {f['evidence']}",f"- Uncertainty: {f['uncertainty_remaining']}",f"- Certainty: {f['certainty']}",""]
    attention=[(r,f) for r in reports for f in r["findings"] if f["severity"]!="GREEN"]
    lines += ["# OWNER ATTENTION REQUIRED",""]
    if not attention: lines += ["NO CURRENT EXCEPTIONS IDENTIFIED FROM THE AVAILABLE EVIDENCE."]
    else:
        for r,f in attention:
            action="VERIFY" if f["severity"]=="YELLOW" else "INVESTIGATE" if f["severity"]=="ORANGE" else "REPLACE / REMOVE / LICENSE"
            lines.append(f"- **{action}** — {r['application']}: `{f.get('path','UNKNOWN')}` — {f['code']}. Do not treat silence as acceptance.")
    return "\n".join(lines)+"\n"

def main()->int:
    p=argparse.ArgumentParser(); p.add_argument("--workspace",type=Path,required=True); p.add_argument("--harness",type=Path,default=Path(__file__).resolve().parents[1]); p.add_argument("--json-out",type=Path,required=True); p.add_argument("--report-out",type=Path,required=True); a=p.parse_args()
    workspace=a.workspace.resolve(); reports=[]
    for root in discover(workspace,a.harness.resolve()):
        report=enrich(IP.audit(root))
        try: report["root"]=root.relative_to(workspace).as_posix() or "."
        except ValueError: report["root"]=root.name
        reports.append(report)
    a.json_out.write_text(json.dumps({"schema":"flins-ip-fleet-audit-v1","reports":reports},indent=2)+"\n",encoding="utf-8"); a.report_out.write_text(render(reports),encoding="utf-8")
    print(f"IP_FLEET_AUDIT_OK projects={len(reports)} findings={sum(len(x['findings']) for x in reports)} destructive_changes=false")
    return 0
if __name__=="__main__": raise SystemExit(main())
